### ISSUE TITLE
Passing color to html, css

### ISSUE THREAD

**Issue by ksvoboda** [dldevinc/django-spectrum#1]
Hello everyone,
I am kinda new to this, and I am creating a small website and I need this.
I wonder if I set color in Django admin, how can I transfer that color to HTML (background color in div, etc)

Thanks

**Comment by pix666** [comment]
Suppose you have the following model: 
```python
# models.py
class Article(models.Model):
    header_color = ColorField(_('color'), default='#000000')
    header = models.CharField(_('header'), max_length=255)
```

You could then do the following:
```django
{# detail.html #}
<h1 style="color: {{ object.header_color }}">{{ object.header }}</h1>
```
